### ISSUE TITLE
Questions: Production-ready and Aeron 

### ISSUE THREAD

**Issue by cloudcompute** [tools4j/elara#4]
Hi @terzerm 

Codebase is pretty huge and you are the only contributor to this repository.. great work !

> Readme file.. The elara library is used productively in applications in the financial industry

Is this library production-ready? If yes, which companies are using it in production? Are there any benchmarks that indicate how efficient the library is, especially the storage and retrieval (snapshots and projections)?

> Readme file.. Default implementation is available for chronicle queue. Elara applications are perfectly suited to integrate with Aeron.

How can I use Aeron (instead of the default chronicle)? Aeron has a module named `Aeron Archive`, so finally it would be responsible for storing the events, am I right? Does Aeron Archive store the data in a key value format?

Thank you.

**Comment by terzerm** [comment]
Hi,

Thanks for your interest in elara!

> Hi @terzerm
>
> Codebase is pretty huge and you are the only contributor to this repository.. great work !

Thanks -- it is work in progress and has grown quite a bit, yes.
 
>> Readme file.. The elara library is used productively in applications in the financial industry
>
> Is this library production-ready? If yes, which companies are using it in production? 

The released version of elara is production ready and is used in one of the big 4 Australian banks in production. The newest released version is 1.7 and is the one recommended to use.

The master branch (or also the feature branches) are work in progress towards a new 2.0 version of elara with quite a few extensions and new concepts.  It is not currently production ready.

> Are there any benchmarks that indicate how efficient the library is, especially the storage and retrieval (snapshots and projections)?

There is no official benchmark, but there are some tests in the HashApplicationTest in samples that are tagged with "perf".  They capture information in metrics files that can be inspected with the message store printer utility mentioned later.

These benchmarks are rather rudimentary, as a rough guide I am clocking over 3M events with 40 byte payload per second.  With larger messages and more complex application logic, this number would come down, but it should be relatively easy to tune an application to get several 100K messages processed per second with elara.

Note that elara does not support snapshots or projections out of the box -- this is all left to the application to implement.  Elara is a specialised event sourcing framework kept to a minimum to achieve lowest possible latency.  It does not allocate objects on the hot path, or create garbage and cause GC pauses.  It also attempts to avoid copying of data whenever possible.

>> Readme file.. Default implementation is available for chronicle queue. Elara applications are perfectly suited to integrate with Aeron.
>
> How can I use Aeron (instead of the default chronicle)? Aeron has a module named Aeron Archive, so finally it would be responsible for storing the events, am I right? Does Aeron Archive store the data in a key value format?

The idea of elara is that it receives messages from outside, and most likely sends messages to the outside world.  This is where aeron can be used (and in fact _is used_ in the mentioned production system).  In the master version, this has been extended to more directly support different message transports, such as aeron and Kafka.

For storing events, only Chronicle Queue is currently available out-of-the box.  However elara integrates Chronicle via message-store API, hence event stores can be plugged in if desired (Note that message store has been renamed from message log in version 1.7). Aaron archive could certainly be implemented as an alternative store, but this is not currently available in elara.  My own experience with aeron archive is that it is not quite trivial to use, especially when iterating through individual entries, since aeron archive stores the data in its native stream format.
Note also that the Chronicle event store comes with message store printer (message log printer in 1.7) to inspect the event store and display them on the console. It can be customised for instance to display app specific event payload.

> 
> Thank you.

Hope this was useful.

**Comment by cloudcompute** [comment]
@terzerm 

Thank you for the quick and detailed response. Great if you can answer few more queries. By the way, it was only yesterday that I had stumbled upon Chronicle, Elara and Aeron.

> Version 1.7 is the one recommended to use

In this case, Chronicle queue stores the events for an unlimited period of time `long-lasting persistence` .. just like we store data in the `customary` relational, documents databases... OR do we need to move the historical data to an Amazon S3 like store?

> The 2.0 version is not currently production ready

If its API is almost stable by now, may we start using it?

> Chronicle Open Source vs Enterprise

It has [Enterprise version](https://chronicle.software/queue-enterprise/) too. The main feature missing in open source is TCP/IP Replication. According to this [source](https://github.com/OpenHFT/Chronicle-Queue/blob/ea/docs/encryption.adoc), Encrypted feature is not available in the open source version.

How can we handle these two especially the data replication for the `backup purpose`.

> Clocking over 3M events with 40 byte payload per second.. several 100K messages processed per second with elara

For B2B commerce like applications that has about. let's say, 500 byte payload.. it'd be okay. In the Kubernetes environment, we can add more server containers.

> Kafka Or Aeron Or Chronicle Queue for real-time streaming

Since Kafka consumes so much of memory and it requires brokers and ZoopKeeper like things, will you recommend using Aeron Or Chronicle instead of Kafka? I think Aeron could be an alternative to Kafka.

**Comment by terzerm** [comment]
> Version 1.7 is the one recommended to use
> In this case, Chronicle queue stores the events for an unlimited period of time long-lasting persistence .. just like we store data in the customary relational, documents databases... OR do we need to move the historical data to an Amazon S3 like store?

This is a good question.  Elara was developed for market systems, where the event store is wiped once per week or day.  If we needed historical data it would be sent into the new session as a command.

For long time storage, I would recommend
- creating snapshots in a parallel or via background process from events
- use latest snapshot to initialise a new event store, e.g. once per week
- store snapshots in long term storage
- maybe also store events in long term storage if this is required

> The 2.0 version is not currently production ready
> If its API is almost stable by now, may we start using it?

At this stage I would not really recommend it, as it is not available in maven yet, and some of the new concepts are not ready yet.  For instance Elara 2.0 supports multi-node event sourcing as illustrated in [docs/elara-apps.jpg](https://github.com/tools4j/elara/blob/master/doc/elara-apps.jpg).  Elara 1.7 does not support that in this way, it runs in a single process.  But of course you can still have multiple readers of the event store.

It really depends a bit on the problem and scale.

> Chronicle Open Source vs Enterprise
> It has [Enterprise version](https://chronicle.software/queue-enterprise/) too. The main feature missing in open [source](https://github.com/OpenHFT/Chronicle-Queue/blob/ea/docs/encryption.adoc) is TCP/IP Replication. According to this source, Encrypted feature is not available in the open source version.
> 
> How can we handle these two especially the data replication for the backup purpose.

For backup you can simply copy the chronicle files. If you want replication for hot/hot resilience it gets a bit more complicated, but reading events from one queue and sending it to another node and storing it in another queue e.g. via TCP is not exactly complicated.  But of course you can also buy the Enterprise Chronicle version if this is an option, this has the additional benefit of getting some supert from that team (they are good, I can recommend them).

> Clocking over 3M events with 40 byte payload per second.. several 100K messages processed per second with elara
> For B2B commerce like applications that has about. let's say, 500 byte payload.. it'd be okay. In the Kubernetes environment, we can add more server containers.

Note sure I follow -- Elara has no payload restriction, but larger payload takes longer to persist, hence the message/second throughput will be affected with large payloads

> Kafka Or Aeron Or Chronicle Queue for real-time streaming
> Since Kafka consumes so much of memory and it requires brokers and ZoopKeeper like things, will you recommend using Aeron Or Chronicle instead of Kafka? I think Aeron could be an alternative to Kafka.

The two can really co-exist.  I would use aeron (UDP or IPC) for local communication (Elara 2.0 also supports TCP, UDP and IPC natively, but I would probably use aeron for UDP and IPC as it is super fast and well established). For longer distance communication I would use Kafka.  Here a cluster exists or is run independently, and elara consumes or produces to some topics from a separate process, and messages are sent to elara e.g. via aeron.

Again, the exact setup really depends on the problem and scale, and how many Microservices are communicating with each other in what way.

**Comment by terzerm** [comment]
> Version 1.7 is the one recommended to use
> In this case, Chronicle queue stores the events for an unlimited period of time long-lasting persistence .. just like we store data in the customary relational, documents databases... OR do we need to move the historical data to an Amazon S3 like store?

This is a good question.  Elara was developed for market systems, where the event store is wiped once per week or day.  If we needed historical data it would be sent into the new session as a command.

For long time storage, I would recommend
- creating snapshots in a parallel or backup process from events
- use latest snapshot to initialise a new event store, e.g. once per week
- store snapshots in long term storage
- maybe also store events in long term storage if this is required

> The 2.0 version is not currently production ready
> If its API is almost stable by now, may we start using it?

At this stage I would not really recommend it, as it is not available in maven yet, and some of the new concepts are not ready yet.  For instance Elara 2.0 supports multi-node event sourcing as illustrated in [docs/elara-apps.jpg](https://github.com/tools4j/elara/blob/master/doc/elara-apps.jpg).  Elara 1.7 does not support that in this way, it runs in a single process.  But of course you can still have multiple readers of the event store.

It really depends a bit on the problem and scale.

> Chronicle Open Source vs Enterprise
> It has [Enterprise version](https://chronicle.software/queue-enterprise/) too. The main feature missing in open [source](https://github.com/OpenHFT/Chronicle-Queue/blob/ea/docs/encryption.adoc) is TCP/IP Replication. According to this source, Encrypted feature is not available in the open source version.
> 
> How can we handle these two especially the data replication for the backup purpose.

For backup you can simply create the chronicle files. If you want replication for hot/hot resilience it gets a bit more complicated, but reading events from one queue and sending it to another node and storing it in another queue e.g. via TCP is not exactly complicated.  But of course you can also buy the Enterprise Chronicle version if this is an option, this has the additional benefit of getting some supert from that team (they are good, I can recommend them).

> Clocking over 3M events with 40 byte payload per second.. several 100K messages processed per second with elara
> For B2B commerce like applications that has about. let's say, 500 byte payload.. it'd be okay. In the Kubernetes environment, we can add more server containers.

Note sure I follow -- Elara has no payload restriction, but larger payload takes longer to persist, hence the message/second throughput will be affected with large payloads

> Kafka Or Aeron Or Chronicle Queue for real-time streaming
> Since Kafka consumes so much of memory and it requires brokers and ZoopKeeper like things, will you recommend using Aeron Or Chronicle instead of Kafka? I think Aeron could be an alternative to Kafka.

The two can really co-exist.  I would use aeron (UDP or IPC) for local communication (Elara 2.0 also supports TCP, UDP and IPC natively, but I would probably use aeron for UDP and IPC as it is super fast and well established). For longer distance communication I would use Kafka.  Here a cluster exists or is run independently, and elara consumes or produces to some topics from a separate process, and messages are sent to elara e.g. via aeron.

Again, the exact setup really depends on the problem and scale, and how many Microservices are communicating with each other in what way.

**Comment by cloudcompute** [comment]
Thank you for sharing the insights with me.

After reading this, I'd prefer using a regular database like Postgres for Event sourcing for few reasons:

- Enterprise version is something I really want to avoid. It leads to vendor lock-in.

- I am new to Aeron and Chronicle

> For longer distance communication I would use Kafka.

In addition to this, Kafka is a standard solution

**Comment by terzerm** [comment]
Welcome -- and thanks for considering elara.

Good luck!
